@startuml Диаграмма сущностей

' title
' [ER diagram] Сущности в проекте "Restobook"
' end title

entity "Ресторан" {
    * идентификатор (число/uuid?)
    --
    * название
    * полное имя юридического лица
    * ИНН
    * комментарий
}

entity "Сотрудник ресторана" {
    * идентификатор (число/uuid?)
    --
    * логин
    * пароль
    * роль
    * фамилия
    * имя
    * отчество
    * комментарий
}

entity "Столик" {
    * идентификатор
    --
    * количество мест
    * состояние
    * описание
}

entity "Бронь" {
    * идентификатор
    --
    * количество человек
    * номер телефона клиента
    * имя клиента
    * время начала
    * длительность
    * фамилия имя отчество открывшего
    * время открытия
    комментарий
}

"Ресторан" ||--|{ "Сотрудник ресторана"
"Ресторан" ||--|{ "Столик"
"Столик" }|--o{ "Бронь"

@enduml