@startuml Диаграмма прецедентов

actor "Администратор вендора" as av
actor "Администратор ресторана" as ar
actor "Сотрудник ресторана" as empl

ar -down-|> empl

empl -left- (Создать бронь)
empl -left- (Редактирование информации о брони)
empl -left- (Просмотр информации о\nконкретной брони)

empl -right- (Просмотр очереди брони\nконкретного стола)
empl -right- (Просмотр очереди брони\nпо всем столам)
empl -right- (Просмотр занятости столов\nво всем зале\nв выбранный момент времени)
empl -right- (Просмотр информации о\nконкретном столе)

empl -down- (Авторизация)
empl -down- (Просмотр информации о\nсвоей учётной записи)
empl -down- (Изменение пароля\nсвоей учётной записи)

ar -right- (Добавить стол)
ar -right- (Редактирование информации о столе)
ar -right- (Просмотр обзорной информации о всех сотрудниках)
ar -right- (Просмотр информации о конкретном сотруднике)
ar -right- (Добавить сотрудника)
ar -right- (Редактирование информации о сотруднике)

av -- (Авторизация на сервисной странице)
av -- (Создание ресторана по заявкеадминистратора ресторана)

@enduml