@startuml Диаграмма активности создания брони

|Посетитель|
start;
:Позвонить для заказа брони>

|Сотрудник ресторана|
:Принять звонок<
:Создать бронь;

if () then (Посетитель позвонил\nотменить бронь)
    :Удалить бронь;
else (Посетитель пришёл)
    :Открыть бронь;
    :Дождаться, когда посетитель уйдёт<
    :Закрыть бронь;
endif;

end;

@enduml