@startuml Диаграмма состояний для брони

' title
'     Диаграмма состояний для столов
' end title

[*] --> Creating : Создание
Creating --> Waiting : Бронь создана,\nожидаются посетители
Waiting -down-> Open : Бронь открыта,\nпосетители пришли
Open -down-> Closed : Бронь закрыта,\nпосетители ушли
Waiting -right-> [*]  : Бронь удалена
Closed --> [*] : Бронь удалена

@enduml