@startuml Диаграмма состояний для столов

' title
'     Диаграмма состояний для столов
' end title

[*] --> Normal : стол создан
Normal -left-> Broken : стол был сломан или по другим причинам\nнепригоден для приёма гостей
Broken -right-> Normal : стол починили
Normal --> [*] : стол удалён
Broken --> [*] : стол удалён

@enduml