@startuml Диаграмма классов

package "Controllers Level" {
    class "Restaurants Controller"
    class "Accounts Controller"
    class "Tables Controller"
    class "Reservations Controller"
}

package "Services Level" {
    class "Restaurants Service"
    class "Accounts Service"
    class "Security Service"
    class "Tables Service"
    class "Reservations Service"
}

package "Persistance Level" {
    class "Restaurants Repository"
    class "Accounts Repository"
    class "Tables Repository"
    class "Reservations Repository"
}

"Restaurants Controller" -down- "Restaurants Service"
"Accounts Controller" -down- "Accounts Service"
"Tables Controller" -down- "Tables Service"
"Reservations Controller" -down- "Reservations Service"

"Restaurants Service" -down- "Restaurants Repository"
"Accounts Service" -down- "Security Service"
"Security Service" -down- "Accounts Repository"
"Security Service" -down- "Restaurants Repository"
"Tables Service" -down- "Tables Repository"
"Reservations Service" -down- "Reservations Repository"
"Reservations Service" -down- "Tables Service"

"Restaurants Repository" -- "Database"
"Accounts Repository" -- "Database"
"Tables Repository" -- "Database"
"Reservations Repository" -- "Database"


@enduml