openapi: '3.0.2'
info:
  title: API Restaurant
  version: '1.0'
  description: API для управления ресторанами и их сотрудниками
paths:
  /restaurants:
    get:
      summary: Получить список ресторанов
      responses:
        '200':
          description: Список ресторанов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
    post:
      summary: Создать ресторан
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Restaurant'
      responses:
        '201':
          description: Ресторан создан
  /employees:
    get:
      summary: Получить список сотрудников
      responses:
        '200':
          description: Список сотрудников
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      summary: Создать сотрудника
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Сотрудник создан
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор сотрудника
        login:
          type: string
          description: Логин сотрудника
        surname:
          type: string
          description: Фамилия сотрудника
        name:
          type: string
          description: Имя сотрудника
        patronymic:
          type: string
          description: Отчество сотрудника
        comment:
          type: string
          description: Комментарий о сотруднике
        changedPass:
          type: boolean
          description: Изменен ли пароль
        restaurant:
          $ref: '#/components/schemas/Restaurant'
      required:
        - login
        - surname
        - name
        - restaurant